ampproject/meta-ac

- working_mode.md
Hi all,
This is a rough working mode document designed to get us started. Your comments and suggestions here are welcome.
> Working mode proposition

- meetings/2019-01-29.md
Agenda: https://github.com/ampproject/meta-ac/issues/4
> Meeting notes 2019-01-29

- README.md
Please let me know your thoughts, or if anyone has any suggestions.
> Add communication methods [#17]

- meetings/2019-03-05.md
> Add minutes for 2019-03-05 meeting

- meetings/2019-03-f2f.md
~Still pending approval of guests for additional notes.~
> Add London F2F minutes

- WORKING_MODE.md
> Define AC membership an election in workmode

- meetings/2019-05-20.md
> Add minutes for 2019-05-20 AC video conf

- meetings/2019-06-03.md
> Add minutes for 2019-06-03 video conf

- README.md
Since we now meet every two weeks I've updated that verbiage in the readme
> Update frequency of video conferences

- meetings/2019-07-29.md
> Add minutes for 2019-07-29 video conf

- meetings/2019-06-17.md
> Add minutes for 2019-06-17 video conf

- meetings/2019-07-01.md
Closes #40.
/cc @ampproject/wg-ui-and-a11y, @nainar, @aghassemi
> Add minutes for 2019-07-01 video conf

- README.md
This info is public from the announcement already.
> Add AC members to README

- README.md
Removing @dknecht as he resigned.
> Removing @dknecht

- meetings/2019-08-26.md
> Add minutes for 2019-08-26 Meeting

- meetings/2019-09-09.md
> Add minutes for 2019-09-09 Meeting

- meetings/2019-09-23.md
- meetings/2019-10-21.md
- meetings/2019-11-04.md
- meetings/2019-12-02.md
- meetings/2019-12-16.md
Closes #53 
Closes #54 
Closes #58 
Closes #59 
Closes #65
> Add minutes for Q4 2019 meetings

- meetings/2020-01-13.md
> Adds minutes for 2020-01-13 Video Call

- meetings/2019-10-08.md
> Adds minutes for 2019-10-08 Face to Face meeting

- meetings/2019-08-12.md
transcribes missing notes content from video; 
Closes #45
> Adds minutes for 2019-08-12 meeting

- meetings/2020-02-10.md
> Adds minutes for 2020-02-10 meeting

- meetings/2020.02.24.md
> adds minutes for 2020-02-24 meeting

- meetings/2020-03-09.md
> adds minutes for 2020-03-09 meeting

- PROCESS.md
As discussed with Tobie, it would be good to capture this list of tasks as well as other types of info related to process.
> Starts a process.md draft with checklists

- WORKING_MODE.md
Addresses https://github.com/ampproject/meta-ac/pull/95/.
/Cc @sumodas
> Add interim member status to working mode

- meetings/2020-04-06.md
> adds minutes for 2020-04-06 meeting

- meetings/2020-04-20.md
> adds minutes for 2020-04-20 meeting

- meetings/2020-05-04.md
> adds minutes for 2020-05-04 meeting

- PROCESS.md
> Adds Slack channel to onboarding process

- meetings/2020-05-18.md
> adds meeting minutes for 2020-05-18 meeting

- README.md
> Remove @levidurfee from active AC members

- meetings/2020-06-01.md
> adds minutes for  2020-06-01 meeting

- meetings/2020-06-15.md
> adds minutes for 2020-06-15 meeting

- meetings/2020-06-29.md
> adds minutes for 2020-06-29 meeting

- PROCESS.md
> Adds Stakeholder Input Process

- meetings/2020-07-13.md
> adds minutes for 2020-07-13 meeting

- meetings/2020-08-10.md
> adds minutes for 2020-08-10 meeting

- meetings/2020-08-24.md
> adds minutes from 2020-08-24 meeting

- meetings/2020-09-21.md
> adds minutes for 2020-09-21 meeting

- meetings/2020-10-05.md
> adds minutes for 2020-10-05 meeting

- meetings/2020-10-19.md
> adds minutes for 2020-10-19 meeting

- meetings/2020-11-02.md
> adds meeting minutes for 2020-11-02 meeting

- README.md
* Adds new AC Members post October's election
* Graduates retiring AC Members to past member list
> Add new AC members

- meetings/2020-11-16.md
> adds minutes for 2020-11-16 meeting

- meetings/2020-11-30.md
> adds minutes for 2020-11-30 meeting

- .github/ISSUE_TEMPLATE/meeting.md
Adds subsections under meeting time for Americas & EMEA and EMEA & APAC meetings
> update template to add EMEA & APAC section

- README.md
- adds GitHub link for @SiddiqiFaizan 
- moves @edent to Alumni list
> updates to roster.md

- meetings/2020-12-14.md
> adds minutes for 2020-12-14 meeting

- meetings/2021-01-11.md
- meetings/2021-01-12.md
> adds meeting minutes for 2021-01-11 and 2021-01-12 meetings

- meetings/2021-01-25.md
- meetings/2021-01-28.md
> adds meeting minutes for 2021-01-25 and 2021-01-28 meetings

- meetings/2021-02-08.md
- meetings/2021-02-09.md
> adds minutes for EMEA/Americas and EMEA/APAC Meetings

- meetings/2021-02-22.md
- meetings/2021-02-23.md
> adds meeting minutes for Americas/EMEA and EMEA/APAC meetings

- meetings/2021-03-08.md
- meetings/2021-03-09.md
> adds minutes for Americas/EEMEA and EMEA/APAC AC meetings

- meetings/2021-04-05.md
- meetings/2021-04-06.md
> adds minutes for Americas / EMEA / APAC meetings

- meetings/2021-05-03.md
- meetings/2021-05-04.md
> Add minutes for 2021-05-03/04 meetings

- meetings/2021-05-17.md
- meetings/2021-05-18.md
> Add minutes for 2021-05-17/18 meetings

- README.md
> Add Dan Walmsley as interim member
